// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu6iwzmbWTZyZYO-z8i-a7atLKqN7m3vU',
    appId: '1:700391740253:web:8695a9e8299052bcaa4eb4',
    messagingSenderId: '700391740253',
    projectId: 'mint-fin-app',
    authDomain: 'mint-fin-app.firebaseapp.com',
    storageBucket: 'mint-fin-app.firebasestorage.app',
    measurementId: 'G-PJ2PN96JNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFWwUL-PGx0bH_vsKVAovBXLFce5QdZD4',
    appId: '1:700391740253:android:89d5a15522569093aa4eb4',
    messagingSenderId: '700391740253',
    projectId: 'mint-fin-app',
    storageBucket: 'mint-fin-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMBh5YQrqO1RnlWqgwpbjgyOqQqLCSlLs',
    appId: '1:700391740253:ios:918a7d2d27b73acbaa4eb4',
    messagingSenderId: '700391740253',
    projectId: 'mint-fin-app',
    storageBucket: 'mint-fin-app.firebasestorage.app',
    iosBundleId: 'com.example.mint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMBh5YQrqO1RnlWqgwpbjgyOqQqLCSlLs',
    appId: '1:700391740253:ios:918a7d2d27b73acbaa4eb4',
    messagingSenderId: '700391740253',
    projectId: 'mint-fin-app',
    storageBucket: 'mint-fin-app.firebasestorage.app',
    iosBundleId: 'com.example.mint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu6iwzmbWTZyZYO-z8i-a7atLKqN7m3vU',
    appId: '1:700391740253:web:923525e1a72c34f0aa4eb4',
    messagingSenderId: '700391740253',
    projectId: 'mint-fin-app',
    authDomain: 'mint-fin-app.firebaseapp.com',
    storageBucket: 'mint-fin-app.firebasestorage.app',
    measurementId: 'G-Q25L812CCM',
  );
}
